
services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: mediacms
      POSTGRES_DB: mediacms
      TZ: Europe/London
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cinemata_network

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
       TZ: Europe/London
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cinemata_network

  # celery_worker:
  #   image: cinemata/cinematacms-dev:latest
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.dev
  #   deploy:
  #     replicas: 1
  #   command: celery -A cms worker -l info
  #   volumes:
  #     - ./:/app/
  #   environment:
  #     DEVELOPMENT_MODE: True
  #     DJANGO_SETTINGS_MODULE: cms.settings
  #     DATABASE_URL: postgres://cinemata:cinemata@db:5432/cinemata
  #     REDIS_URL: redis://redis:6379/0
  #     DEBUG: True
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - cinemata_network

  # celery_beat:
  #   image: cinemata/cinematacms-dev:latest
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.dev
  #   command: celery -A cms beat -l info
  #   volumes:
  #     - ./:/app/
  #   environment:
  #     DEVELOPMENT_MODE: True
  #     DJANGO_SETTINGS_MODULE: cms.settings
  #     DATABASE_URL: postgres://cinemata:cinemata@db:5432/cinemata
  #     REDIS_URL: redis://redis:6379/0
  #     DEBUG: True
  #   depends_on:
  #     - celery_worker
  #   networks:
  #     - cinemata_network

volumes:
  postgres_data:
  redis_data:

networks:
  cinemata_network:
    driver: bridge